config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index' # default Rails welcome page

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "/#{APP_CONFIG[:sitekey]}" do
    root to: 'authors#index'

    resources :authors
    resources :chapters

    # Authentication
    get "signup" => "users#new",        as: :signup
    post "users" => "users#create",     as: :create_user

    get "login"  => "sessions#new",     as: :login
    post "login" => "sessions#create",  as: :create_login
    get "logout" => "sessions#destroy", as: :logout

    # AJAX end points
    get  "authors/letters"                => "authors#author_letters"
    get  "authors/letters/:letter/:page"  => "authors#authors"

    post "authors/import/:author_id"      => "authors#import_author"
    get "authors/check/:author_id"        => "authors#check"

    get  "items/author/:author_id"   => "items#get_by_author", as: :item_by_author

    post "items/import/:type/:id"    => "items#import",        as: :item_import
    post "items/mark/:type/:id"      => "items#mark",          as: :item_mark
    post "items/check/:type/:id"     => "items#check",         as: :item_check
    post "items/dni/:type/:id"       => "items#dni",           as: :item_dni
    get  "items/audit/:type/:id"     => "items#audit",         as: :item_audit

    # Admin features
    resource :archive_configs, path: :config
    resources :archive_configs, path: :config, only: [:edit, :show, :update]

    get "stats/api", to: "stats#stats"
    get "stats", to: "authors#index"

    mount ActionCable.server => '/cable'
  end
end

app/models/archive_config.rb
class ArchiveConfig < ApplicationRecord
  validates_presence_of :name, :host
  
  def self.archive_config
    find_by_key(APP_CONFIG[:sitekey])
  end
  
  def to_hash
    as_json
  end
end

app/controllers/archive_configs_controller.rb
class ArchiveConfigsController < ApplicationController
  include Item
  
  before_action :authorize

  # GET /archive_configs/1
  def show
  end

  # GET /archive_configs/1/edit
  def edit
  end

  # PATCH/PUT /archive_configs/1
  def update
    notice = "Archive config was successfully updated."
    host = params[:archive_config][:host]
    new_host = host != @active_host
    
    if @archive_config.update(archive_config_params)
      if new_host
        load_config
        reset_flags
        notice << " The host has been changed: all authors, stories and storylinks are now marked as ready to import."
      end
      redirect_to @archive_config, notice: notice
    else
      render :edit
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def archive_config_params
    params.fetch(:archive_config, {}).permit(:key, :name, :fandom, :stories_note, :bookmarks_note,
                                             :send_email, :post_preview, :items_per_page,
                                             :archivist, :collection_name, :imported, :not_imported,
                                             :host)
  end
end

app/views/archive_configs/edit.html.erb
<%= render partial: "shared/navigation" %>
<div class="container">
  <h1>Edit archive config</h1>

  <%= form_for(@archive_config) do |f| %>
    <% if @archive_config.errors.any? %>
      <div id="alert alert-danger error_explanation">
        <h2><%= pluralize(@archive_config.errors.count, "error") %> stopped this archive config from being saved:</h2>

        <ul>
          <% @archive_config.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <% host_list = ENV['RAILS_ENV'] == "production" ? [:test, :live] : [:local, :test, :live] %>
      <%= f.label :host %>
      <%= f.select :host, host_list, {}, class: "form-control" %>
      <small id="hostHelp" class="form-text">Warning: changing this will clear imported and do not import flags and AO3
        urls from all stories and story links
      </small>
    </div>

    <div class="field form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :fandom %>
      <%= f.text_field :fandom, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :stories_note %>
      <%= f.text_area :stories_note, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :bookmarks_note %>
      <%= f.text_area :bookmarks_note, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :send_email %>
      <%= f.check_box :send_email %>
    </div>

    <div class="field form-group">
      <%= f.label :post_preview %>
      <%= f.check_box :post_preview %>
    </div>

    <div class="field form-group">
      <%= f.label :archivist %>
      <%= f.text_field :archivist, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :collection_name %>
      <%= f.text_field :collection_name, class: "form-control" %>
    </div>

    <div class="actions">
      <%= f.submit "Update archive config", class: "btn btn-primary" %>
      <%= link_to "Back to archive config", @archive_config, class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/archive_configs/show.html.erb
<%= render partial: "shared/navigation" %>

<div class="container">
  <h1>Archive config</h1>

  <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>

  <p>
    <strong>Host:</strong>
    <%= @archive_config.host %>
  </p>

  <p>
    <strong>Key:</strong>
    <%= @archive_config.key %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @archive_config.name %>
  </p>

  <p>
    <strong>Default fandom:</strong>
    <%= @archive_config.fandom %>
  </p>

  <p>
    <strong>Stories note:</strong>
    <%= @archive_config.stories_note %>
  </p>

  <p>
    <strong>Bookmarks note:</strong>
    <%= @archive_config.bookmarks_note %>
  </p>

  <p>
    <strong>Send email:</strong>
    <%= @archive_config.send_email %>
  </p>

  <p>
    <strong>Post preview:</strong>
    <%= @archive_config.post_preview %>
  </p>

  <p>
    <strong>Archivist:</strong>
    <%= @archive_config.archivist %>
  </p>

  <p>
    <strong>Collection name:</strong>
    <%= @archive_config.collection_name %>
  </p>

  <%= link_to 'Edit', edit_archive_config_path(@archive_config), class: "btn btn-primary" %>
</div>