config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index' # default Rails welcome page

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "/#{APP_CONFIG[:sitekey]}" do
    root to: 'authors#index'

    resources :authors
    resources :chapters

    # Authentication
    get "signup" => "users#new",        as: :signup
    post "users" => "users#create",     as: :create_user

    get "login"  => "sessions#new",     as: :login
    post "login" => "sessions#create",  as: :create_login
    get "logout" => "sessions#destroy", as: :logout

    # AJAX end points
    get  "authors/letters"                => "authors#author_letters"
    get  "authors/letters/:letter/:page"  => "authors#authors"

    post "authors/import/:author_id"      => "authors#import_author"
    get "authors/check/:author_id"        => "authors#check"

    get  "items/author/:author_id"   => "items#get_by_author", as: :item_by_author

    post "items/import/:type/:id"    => "items#import",        as: :item_import
    post "items/mark/:type/:id"      => "items#mark",          as: :item_mark
    post "items/check/:type/:id"     => "items#check",         as: :item_check
    post "items/dni/:type/:id"       => "items#dni",           as: :item_dni
    get  "items/audit/:type/:id"     => "items#audit",         as: :item_audit

    # Admin features
    resource :archive_configs, path: :config
    resources :archive_configs, path: :config, only: [:edit, :show, :update]

    get "stats/api", to: "stats#stats"
    get "stats", to: "authors#index"

    mount ActionCable.server => '/cable'
  end
end

app/views/shared/_meta.html.erb
<%
  is_story = type == :story
  css_class = item.imported ? "imported" : ""
  css_class += " do_not_import" if item.do_not_import
  css_class += " broken_link" if item.has_attribute?(:broken_link) && item.broken_link
  css_class += " #{type}"
  item_id = item_id(type, item.id)
%>

<section class="item <%= css_class %>"
         id="<%= item_id %>">

  <div class="row col-12 align-items-center" style="padding-right: 0px">
    <!-- Title and authors -->
    <h4 class="col col-lg-4 col-md-12">
      <span class="badge badge-info"><%= item.id %></span>
      <a href="<%= "#details-#{item_id}" %>" data-toggle="collapse">
        <% if (is_story || type == :coauthored_story) && item.chapters.size > 0 %>
          <span><%= item.title %></span>
        <% else %>
          <a href="<%= item.url %>"><%= item.title %></a>
        <% end %>

        <% if !author_view || item.coauthor? %>
        <span>by <b><%= item.author.name %></b>
          <% if item.coauthor? %>
            <span>and <b><%= item.coauthor.name %></b></span>
          <% end %>
        </span>
        <% end %>

        <% if is_story %>
          (<%= item.chapters.size %> chapters)
        <% else %>
          <a href="<%= "#details-#{type}-#{item.id}" %>" data-toggle="collapse">(expand)</a>
        <% end %>
        <i id="<%= "info-img-#{item_id}" %>"
           class="fa fa-info-circle"
           aria-hidden="true"
           style="display: <%= item.audits.empty? ? "none" : "inline-block" %>"></i>
      </a>
    </h4>

    <!-- BUTTONS -->
    <div class="col col-lg-8 col-sm-12 extra-space text-right" style="padding-right: 0px;">
      <% if type != :coauthored_story %>
        <!-- Import -->
        <span id="<%= "import-#{item_id}" %>">
          <% if item.imported %>
            <a href="<%= item.ao3_url %>" target="_blank"><%= item.ao3_url %></a>
          <% else %>
              <%= link_to "Import", item_import_path(type, item.id),
                          id: "item-import-#{item_id}", remote: true,
                          class: "btn-sm btn-import", hidden: item.do_not_import,
                          data: {
                            method: :post, button: :import,
                            item: item.id, type: type
                          } %>
          <% end %>
        </span>
        <!-- Mark as import - we don't think we need this anymore
        <span>&nbsp;</span>
        <% #= link_to (item.imported ? "Mark as NOT imported" : "Mark as imported"), item_mark_path(type, item.id),
           #         id: "item-mark-#{item_id}", remote: true,
           #         data: { method: :post, button: :mark, item: item.id, type: type } %>
        -->
        <span>&nbsp;</span>
        <%= link_to "Check if imported", item_check_path(type, item.id),
                    id: "item-check-#{item_id}", remote: true,
                    class: "btn-sm btn-check",
                    data: { method: :post, button: :check, item: item.id, type: type } %>
        <span>&nbsp;</span>
        <%= link_to (item.do_not_import ? "Mark as ALLOW import" : "Mark as do NOT import"), item_dni_path(type, item.id),
                    id: "item-dni-#{item_id}", remote: true,
                    class: "btn-sm btn-dni", confirm: "Are you sure this #{type} should not be imported?",
                    data: { method: :post, button: :dni, item: item.id, type: type } %>
      <% end %>
    </div>
  </div>

  <div class="w-100"></div>

  <!-- Blurb -->
  <div id="<%= "details-#{item_id}" %>" class="details row col-12 collapse">
    <div id="<%= "meta-#{item_id}" %>" class="blurb col-lg-6 col-md-12">
      
    </div><!-- end meta -->

    <!-- Audit -->
    <div id="<%= "audit-#{item_id}" %>" class="audit col-lg-6 col-md-12">
      <% item.audits.each do |audit| %>
        <%= audit.created_at %> - [<%= audit.remote_address %>] <%= audit.comment %><br/>
      <% end %>
    </div>
  </div> <!-- end details -->

    <div class="message">
      <% if @api_response.present? && @api_response[item_id.to_sym] %>
        <ul>
          <% @api_response[item_id.to_sym][:messages].each do |s| %>
            <li><%= s.html_safe %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
</section>

app/views/shared/_navigation.html.erb
<%= react_component("navigation/Navigation", {
    data: {
        logo_path: asset_path("Opendoors.png"),
        letter: params[:letter] || 'A',
        config: @api_config.merge(@archive_config),
        current_user: current_user&.name || '',
    },
    page: params[:page] || '1',
    config_path: archive_config_path(@archive_config)
}) %>