config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index' # default Rails welcome page

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "/#{APP_CONFIG[:sitekey]}" do
    root to: 'authors#index'

    resources :authors
    resources :chapters

    # Authentication
    get "signup" => "users#new",        as: :signup
    post "users" => "users#create",     as: :create_user

    get "login"  => "sessions#new",     as: :login
    post "login" => "sessions#create",  as: :create_login
    get "logout" => "sessions#destroy", as: :logout

    # AJAX end points
    get  "authors/letters"                => "authors#author_letters"
    get  "authors/letters/:letter/:page"  => "authors#authors"

    post "authors/import/:author_id"      => "authors#import_author"
    get "authors/check/:author_id"        => "authors#check"

    get  "items/author/:author_id"   => "items#get_by_author", as: :item_by_author

    post "items/import/:type/:id"    => "items#import",        as: :item_import
    post "items/mark/:type/:id"      => "items#mark",          as: :item_mark
    post "items/check/:type/:id"     => "items#check",         as: :item_check
    post "items/dni/:type/:id"       => "items#dni",           as: :item_dni
    get  "items/audit/:type/:id"     => "items#audit",         as: :item_audit

    # Admin features
    resource :archive_configs, path: :config
    resources :archive_configs, path: :config, only: [:edit, :show, :update]

    get "stats/api", to: "stats#stats"
    get "stats", to: "authors#index"

    mount ActionCable.server => '/cable'
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  audited comment_required: true

  belongs_to :story

  self.primary_key = "id"
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def show
    @chapter = Chapter.find(params[:id])
  end
end

app/views/chapters/show.html.erb
<%= render partial: "shared/navigation" %>

<div class="container">
  <%
    is_first_chapter = @chapter.position <= 1
    story = @chapter.story

    def tag_html(tag_name, tag)
      if tag && !tag.blank?
        "<br/><b>#{tag_name}:</b> #{tag}"
      else
        "<br/><b>No #{tag_name.downcase}</b>"
      end
    end
  %>

  <% content_for :title, story.title + " - Chapter #{@chapter.position}" %>

  <!-- Body Content -->
  <h2>
    <span class="badge badge-info"><%= story.id %></span>
    <%= story.title %>
    <small>by <a href="<%= "#{authors_path}?letter=#{story.author.name[0].upcase}" %>"><%= story.author.name %></a><%= story.coauthor? ? " and #{story.coauthor.name}" : "" %></small>
  </h2>
  <h3><span class="badge badge-info"><%= @chapter.id %></span> <%= @chapter.title %></h3>

  <% if story.imported && story.ao3_url %>
    <div class="alert alert-success" role="alert">
      Story imported to <a href="<%= story.ao3_url %>" target="_blank"><%= story.ao3_url %></a>
    </div>
  <% end %>

  <div class="invisible"><b>Title:</b> <%= story.title %></div>

  <div class="card">
    <div class="card-text">
      <% if is_first_chapter && @archive_config.present? %>
        <b>Note:</b><br/>
        <div style="border: 1px silver solid;">
          <%= raw @archive_config.stories_note %>
          <% if story.notes.present? %>
            <br/><br/>
            <p>--</p>
            <span>Author's notes:</span> <%= raw story.notes %>
          <% end %>
        </div>
      <% end %>

      <!-- Hide summary so it doesn't get imported as the chapter summary (AO3-6191) -->

      <%= raw tag_html("Rating", story.rating) %>
      <%= raw tag_html("Warnings", story.warnings) %>
      <%= raw tag_html("Categories", story.categories) %>
      <%= raw tag_html("Fandoms", story.fandoms) %>
      <%= raw tag_html("Relationships", story.relationships) %>
      <%= raw tag_html("Characters", story.characters) %>
      <%= raw tag_html("Tags", story.tags) %>

      <!--// DON'T INDENT start tag - THIS *ALWAYS* GETS SCRAPED -->
      <!-- First chapter in single chapter work or non-first in multichapter -> updated date -->
      <br/>
      <b>Date:</b> <%=
      if (is_first_chapter && story.chapters.size == 1) || (!is_first_chapter && story.chapters.size > 1)
        (story.updated || story.date || DateTime.now).to_s(:iso_date)
      elsif is_first_chapter && story.chapters.size > 1
        (story.date || story.updated || DateTime.now).to_s(:iso_date)
      end
    %>
      <br/>
      <b>Chapter Title:</b> <%= @chapter.title.blank? ? "Chapter #{@chapter.position}" : @chapter.title %>
      <br/><b>Chapter Number:</b> <%= @chapter.position %>

      <% if @chapter.date.present? %>
        <br/><b>Chapter posted:</b> <%= @chapter.date.to_s(:iso_date) %>
      <% end %>
    </div>
  </div>

  <div class="chapter-content" style="white-space: pre-line">
    <% if @chapter.notes.present? %>
      <div class="form-group">
        <label class="col-sm-2">Author's notes:</label> <%= raw @chapter.notes %>
      </div>
      <hr/>
    <% end %>
    <%= raw @chapter.text %>
  </div>

</div>